name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    uses: consenlabs/tokenlon-contracts-lib-js/.github/workflows/build.yaml@5928d32dd6cafde205034229c0369081d369001f
    secrets: inherit
