# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn run lint

      - name: Test
        env:
          NETWORK: mainnet
          FORK_NODE_RPC_URL: ${{ secrets.MAINNET_NODE_RPC_URL }}
          FORK_BLOCK_NUMBER: 14995000
        run: |
          yarn run compile-sol
          yarn run test
